config/routes.rb
Rails.application.routes.draw do
  resources :snippets
  root 'snippets#index'

end

app/models/snippet.rb
class Snippet < ActiveRecord::Base
    validates :snippet, presence: true
    
    def self.search(search)
	    where("snippet LIKE ?", "%#{search}%")
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController
  before_action :set_snippet, only: [:show, :edit, :update, :destroy]

  # GET /snippets
  # GET /snippets.json
  def index
    if params[:search]
		@snippets = Snippet.search(params[:search]).order("id DESC").page params[:page]
	else
		@snippets = Snippet.order("id DESC").page params[:page]
	end
  end

  # GET /snippets/1
  # GET /snippets/1.json
  def show
  end

  # GET /snippets/new
  def new
    @snippet = Snippet.new
  end

  # GET /snippets/1/edit
  def edit
  end

  # POST /snippets
  # POST /snippets.json
  def create
    @snippet = Snippet.new(snippet_params)

    respond_to do |format|
      if @snippet.save
        format.html { redirect_to @snippet, notice: 'Snippet was successfully created.' }
        format.json { render :show, status: :created, location: @snippet }
      else
        format.html { render :new }
        format.json { render json: @snippet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /snippets/1
  # PATCH/PUT /snippets/1.json
  def update
    respond_to do |format|
      if @snippet.update(snippet_params)
        format.html { redirect_to @snippet, notice: 'Snippet was successfully updated.' }
        format.json { render :show, status: :ok, location: @snippet }
      else
        format.html { render :edit }
        format.json { render json: @snippet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /snippets/1
  # DELETE /snippets/1.json
  def destroy
    @snippet.destroy
    respond_to do |format|
      format.html { redirect_to snippets_url, notice: 'Snippet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_snippet
      @snippet = Snippet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def snippet_params
      params.require(:snippet).permit(:snippet, :is_private)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/snippets_helper.rb
module SnippetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Codesnippet</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/snippets/_form.html.erb
<%= form_for(@snippet) do |f| %>
  <% if @snippet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@snippet.errors.count, "error") %> prohibited this snippet from being saved:</h2>

      <ul>
      <% @snippet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :snippet %><br>
    <%= f.text_area :snippet, :cols => "80", :rows => "10" %>
  </div>
  <div class="field">
    <%= f.label :is_private %><br>
    <%= f.check_box :is_private %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/snippets/edit.html.erb
<h1>Editing Snippet</h1>

<%= render 'form' %>

<%= link_to 'Show', @snippet %> |
<%= link_to 'Back', snippets_path %>

app/views/snippets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Snippets</h1>
<%= link_to 'Create Snippet', new_snippet_path %>

<%= form_tag(snippets_path, :method => "get", id: "search-form") do %>
	<p>
		<%= text_field_tag :search, params[:search], placeholder: "Search Snipppet" %>
		<%= submit_tag "Search" %>
	</p>
<% end %>
<div id="snippet_listing">
    <% if @snippets.present? %>
	
	<%= page_entries_info @snippets, entry_name: "Records" %>
	
		<table>
		  <thead>
			<tr>
			  <th>Snippet</th>
			  <th colspan="2"></th>
			</tr>
		  </thead>

		  <tbody>
			<% @snippets.each do |snippet| %>
			  <tr>
				
				<td><%= link_to truncate(snippet.snippet, :ommision => "Read More", :length => 50), snippet_path(snippet) %></td>
				<td><%= link_to 'Show', snippet %></td>
				<td><%= link_to 'Edit', edit_snippet_path(snippet) %></td>
				<td><%= link_to 'Destroy', snippet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
			  </tr>
			<% end %>
		  </tbody>
		</table>
	    <%= paginate @snippets %>
	<% else %>
	   <p>There are no snippets containing the term(s) <%= params[:search] %>.</p>
	<% end %>
</div>
<br>

<%= link_to 'New Snippet', new_snippet_path %>

app/views/snippets/new.html.erb
<h1>New Snippet</h1>

<%= render 'form' %>

<%= link_to 'Back', snippets_path %>

app/views/snippets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Snippet:</strong>
  <%= @snippet.snippet %>
</p>



<%= link_to 'Edit', edit_snippet_path(@snippet) %> |
<%= link_to 'Back', snippets_path %>